import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Cairo } from 'next/font/google'
// import { Inter } from "next/font/google";

import UniversityFooter from "@/components/Footer";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

const cairo = Cairo({
  subsets: ["latin"],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "الجامعة دمياط الاهلية",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" className={cairo.className}>
    //   <body className={cairo.className}>

    <html lang="ar" className={` ${cairo.variable} ${cairo.className}`}>
      <body className={` ${cairo.variable}`}>
        <Header />
        <main className="pt-[clamp(44.40px,11.56vw,116px)]">
          {children}
        </main>
        <UniversityFooter />
      </body>
    </html>
  );
}
